/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xinlan_addnum_Native */

#ifndef _Included_com_xinlan_addnum_Native
#define _Included_com_xinlan_addnum_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xinlan_addnum_Native
 * Method:    addNum
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_xinlan_addnum_Native_addNum
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
